### ISSUE TITLE
Wrong type when accessing an array with multiple items

### ISSUE THREAD

**Issue by nicofishman** [g-makarov/dot-path-value#1]
The type of the item accessed is a union of all the types of the items in the array:

```ts
const obj = {
    a: {
        b: [
            {
                c: 1,
            },
            'test',
            true
        ],
    },
};

const value = getByPath(obj, 'a.b.1');
```

In this case the type of `value` is `string | boolean | { c: number; }` where it should be `string`

**Comment by g-makarov** [comment]
It seems that Typescript may not allow you to do this due to its inference of arrays.

The type of `const b = [{ c: 1 }, 'test', true]` is `(string | boolean | { c: number; })[]`, which means that you cannot get the correct type of each element in the array.

However, you can define your `obj` with `as const` keyword, like this:
```
const obj = {
  a: {
    b: [
      {
        c: 1,
      },
      'test',
      true
    ],
  },
} as const;
```
This will give you the exact type of the desired path, which in this case would be "test".

Additionally, the Typescript 5.0 beta release includes support for [const type parameters](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#const-type-parameters), which could be useful for this purpose.
